### ISSUE TITLE
Odmiana wyrazów

### ISSUE THREAD

**Issue by WMP** [Ludeon/RimWorld-Polish#1]
"Podczas deszczu nastąpiło zwarcie w baterie i wybuchł pożar." - da się coś z tym zrobić?

**Comment by Cwaniaczek021** [comment]
Cześć. Nowy jestem. :)

**Comment by Reco21** [comment]
Witaj :)


2016-02-03 7:03 GMT+01:00 Cwaniaczek021 <notifications@github.com>:

**Comment by maxdyner** [comment]
witam :P

**Comment by Cwaniaczek021** [comment]
Zostałem dodany prze ludeon do grupy tłumaczy, czy to jest ta?

**Comment by Reco21** [comment]
Tak, tutaj tłumaczymy RimWorld'a na język polski.

2016-02-06 17:17 GMT+01:00 Cwaniaczek021 <notifications@github.com>:

**Comment by Cwaniaczek021** [comment]
Yhym, czyli tylko zaproszeni mogą tu pisać tak? :D

**Comment by Reco21** [comment]
a Tago nei wiem :D

2016-02-07 19:40 GMT+01:00 Cwaniaczek021 <notifications@github.com>:
