### ISSUE TITLE
Brak odmiany płci - 0_gender

### ISSUE THREAD

**Issue by ImperatorEdi** [Ludeon/RimWorld-Polish#140]
Witam,

Grając na oficjalnym spolszczeniu, jak i pobranym stąd, widzę, że w kreatorze postaci (pionków) brakuje płci. Zamiast tego jest {0_gender ? niezdolny : niezdolna}. Problem jest też w widoku postaci, przy umiejętnościach. Zamiast np. ekspert jest {0_gender ? ekspert : ekspertka}.

**Comment by Arczi008TV** [comment]
To chyba jakieś przestarzałe masz. Bo to jest dawno poprawione
