### ISSUE TITLE
"Wymagany poziom umiejętności" jest za długie

### ISSUE THREAD

**Issue by Bukaj-2** [Ludeon/RimWorld-Polish#141]
Witam. Natrafiłem na pewien problem w grze, a mianowicie w menu szczegółów wytwarzania pojawia się pole z komunikatem na przykład
Wymagany poziom umiejętności rzemieślnictwo 

Problem w tym, że tekst ten jest za długi i zostaje zawinięty do następnego rzędu, przez co nie jest wyświetlany pasek umożliwiający ustawieni poziomu tej umiejętności. W angielskiej wersji ta wiadomość jest krótsza (mieści się w jednej linijce) i problem nie występuje.
Proponuje skrócenie tego tekstu do na przykład "Wymagany poziom" lub "Poziom umiejętności"

Tekst ten znajduje się 
RimWorld-Polish\Core\Keyed\Dialogs_Various.xml
wiersz 237
  <AllowedSkillRange>Wymagany poziom umiejętności {0}:</AllowedSkillRange>

Dziękuje i pozdrawiam

**Comment by Arczi008TV** [comment]
Dzięki, poprawię.
