### ISSUE TITLE
Ale szanujmy język.

### ISSUE THREAD

**Issue by Kunegard** [Ludeon/RimWorld-Polish#20]
Uszanowanko, piszę tutaj, by nie zniknęło:
Tłumacząc, bądźmy w stu procentach pewni, że robimy to w sposób dobry. Innymi słowy - szanujemy język. Upewniamy się, czy stosujemy poprawnie przecinki, a gdy czegoś nie wiemy, to właśnie to dodajemy do opisu zmian. No i przede wszystkim - upewniamy się, czy ta zmiana będzie pasować do reszty gry. Czy przypadkiem słowo "dark" (m.in. ciemny) nie będzie lepiej zrobić na "mroczny" - bo z kontekstu wynika, że chodzi o dark man, a więc mrocznego gościa. 

Mamy korektorkę w naszej drużynie, Nalthe (e-mail: kamila@borto.pl w razie czego). Przeglądała ostatnio zmiany, coś się stało - kilka plików zostało chyba wgranych na nowo albo poprawionych według własnego widzimisię. Oszczędzając zbędnego gadania - potworki, potworki wychodzą, gdy tak się robi. 

Moja rada:
Sprawdzajcie tłumaczenie niemieckie, serio. To nie wstyd, a wpajany za młodu "język wroga", o którym tak się mówiło, że trzeba go znać - to prawda. Nie rozumiesz znaczenia podanego słowa - sprawdź w niemieckim repozytorium, a drzewo znaczeń zawęzi się do (najpewniej) jednej gałązki.

**Comment by Fejm** [comment]
Gorzej jak się nie zna niemieckiego :)

**Comment by Nalthe** [comment]
Słowniki nie bolą.

I błagam, odpuśćcie sobie poprawianie przecinków i ortografii. Spędziłam nad korektą kilkadziesiąt dni, żeby teraz wejść i zobaczyć "wydażenie".

**Comment by Fejm** [comment]
Słownik gramatyki nie tłumaczy. Ja tłumaczę z angielskiego bo ten język znam. Poza tym każdy ma prawo się pomylić :)

**Comment by Nalthe** [comment]
Ale pojedyncze słowa tłumaczą. Przykład? "Ghostfaced". O twarzy ducha, serio? Takich przykładów jest mnóstwo. Nie tłumaczcie czegoś, czego nie jesteście pewni, przynajmniej inni będą wiedzieli, że trzeba to skontrolować (albo dajcie komentarz, przecież się da), a nie będę musiała sprawdzać WSZYSTKO od początku, porównując z angielską wersją. No i sprawdzajcie konteksty, spójrzcie, że to mają być przymiotniki, a nie rzeczowniki (przykładowo).

A co do pomyłek - pomylić tak, ale nie jeśli daną rzecz sprawdzałam już co najmniej trzy razy i ciągle wraca do pierwotnej wersji, która jest zwyczajnie błędna. To zwyczajny brak szacunku do pracy innych - poświęciłam na tę grę mnóstwo czasu, za który normalnie mi się płaci, ale tutaj robię to, bo zwyczajnie szanuję dzieło. No ale cholera, nie będę poprawiać jednej i tej samej rzeczy 20 razy, bo komuś się wydaje, że wie lepiej D:

**Comment by Fejm** [comment]
No więc powiem tak, patrzę na to co teraz dodajecie to faktycznie, dziesięć razy poprawiane to samo. Trochę słabo to wygląda faktycznie.

**Comment by Bucu88** [comment]
A wystarczy żeby każdy robił swoją gałąź. I &quot;korektorka&quot; po sprawdzeniu zmian scalala by ją z masterem. I po problemie...

**Comment by Nalthe** [comment]
Nie zajmuję się tylko korektą, skąd ten wniosek? xD Poprawiam po Was, bo robicie karygodne błędy, no ale poprawiać 100 razy nie będę. Po prostu szanujcie to, co się robi xD Wracacie po x czasu, dodajecie durne komentarze "I'm back", zamiast oznaczać numerem aktualizacji, żeby było łatwo się zorientować i NAGLE narzucacie swoje zasady. Przykro mi, ale tak to działać nie będzie - inni może dali sobie narzucać bzdury, ja swojej pracy zniszczyć nie pozwolę, bo zbyt dużo czasu na to poświęciłam.

**Comment by Bucu88** [comment]
No jasne lepiej przyjść jako świeżak i się rządzić :) albo pracujemy jako zespół albo w bardzo prosty sposób będziemy sobie robić pod górkę, uwierz mi, ja też poświęciłem dużo czasu na tłumaczenie tej gry a takie coś jak wrzucanie śmieci na mastera nawet na 5 godzin może komuś popsuć plany w tłumaczeniu.. także proszę załóż sobie swój własny branch tam się baw, a nie zaśmiecasz mastera. Prosiłbym też nie mówić do mnie Wy bo to co najmniej dziwne... 
 

    On Friday, August 5, 2016 11:09 AM, Nika <notifications@github.com> wrote:
 

 Nie zajmuję się tylko korektą, skąd ten wniosek? xD Poprawiam po Was, bo robicie karygodne błędy, no ale poprawiać 100 razy nie będę. Po prostu szanujcie to, co się robi xD Wracacie po x czasu, dodajecie durne komentarze "I'm back", zamiast oznaczać numerem aktualizacji, żeby było łatwo się zorientować i NAGLE narzucacie swoje zasady. Przykro mi, ale tak to działać nie będzie - inni może dali sobie narzucać bzdury, ja swojej pracy zniszczyć nie pozwolę, bo zbyt dużo czasu na to poświęciłam. —

**Comment by Kunegard** [comment]
Dziesięć razy poprawiane to samo, bo raz napisane poprawnie być nie może. "Pruszy"? "Ważywa"? W ogóle patrzycie, co jest poprawiane? 
"Każdy robił własną gałąź"? To nie korporacja, w której Staszek odpowiada za kupowanie papieru, Basia za jego spinanie, a Tomuś za doręczanie. Tak, jak robimy, jest najefektywniej. To nie jest tak, że każdy jeden z nas "robi własne tłumaczenie". Robimy jedno. W creditach też napisalibyście, kto którą część robił?

**Comment by Kunegard** [comment]
Zarówno korektorka jak i my odpowiadamy za jedną czynność. Te "śmieci", o których tak pięknie mówisz, to RimWorld i jego pliki.

**Comment by Nalthe** [comment]
Świeżak? XDD Nie znasz mojego dorobku, więc się uprzejmie nie wypowiadaj. Nie podoba się - cóż, nie zmuszam do współpracy, ale sam sobie pracuj na własnej gałęzi. Twoje "ważywa" to śmieci. Nie znasz polskiego = nie zajmuj się tłumaczeniem.

**Comment by Nalthe** [comment]
I szczerze, mam gdzieś Twoje plany w tłumaczeniu, jeśli zrobię to szybciej, wcześniej i nie będę mieć tam "ważyw" czy "downed" jako "przygnębionego", gdzie w grze chodzi o rannego, czego najpewniej nie sprawdziłeś, bo robisz to tak cudownie i wspaniale, och, ach.

**Comment by Bucu88** [comment]
Ewidentnie nie rozumiecie o co mi chodzi... cóż trudno jeżeli chcecie możemy sobie wchodzić w drogę tłumaczyć, 10 razy to samo, poprawiać jedno po drugim... jeżeli nie rozumiecie zasady działania "gałęzi" well that`s not my problem.Pozdrawiam
 

    On Friday, August 5, 2016 11:46 AM, Nika <notifications@github.com> wrote:
 

 Świeżak? XDD Nie znasz mojego dorobku, więc się uprzejmie nie wypowiadaj. Nie podoba się - cóż, nie zmuszam do współpracy, ale sam sobie pracuj na własnej gałęzi. Twoje "ważywa" to śmieci. Nie znasz polskiego = nie zajmuj się tłumaczeniem. —

**Comment by Kunegard** [comment]
A żebyś wiedział! Będziemy. Do skutku, aż znikną wszystkie "ważywa" z tłumaczenia. Bo jedna osoba też może popełniać błędy.

**Comment by Nalthe** [comment]
Och, no tak, bo Tobie wolno pracować w masterze, innym nie. Ale lepiej powiedzieć, że nie rozumieją, o co chodzi.

**Comment by ApocArkhesir** [comment]
Chciałbym tylko powiedzieć, że praca bezpośrednio na masterze to jest jakiś
nieśmieszny dowcip. Im szybciej zrozumiecie na czym polega rozproszony
system kontroli wersji tym lepiej dla was, waszego czasu i nerwów. Polecam
zapoznać się z Gitem bo kopaniem pod sobą dołków do niczego nie dojdziecie.

05.08.2016 11:54 "Nika" <notifications@github.com> napisał(a):

**Comment by Fejm** [comment]
Popieram przedmówcę, dodajcie 200 commitów który każdy ma w nazwie Alpha 14 i wcale nie wiadomo co aktualizujecie, co dodajcie. Ogólnie rzecz biorąc to można dodawać kilka plików na raz i wtedy wygląda to o niebo lepiej. Tak samo ja, wczoraj chciałem dla "Was" potłumaczyć ale żeby mój branch nadążył za waszym i dało się go scalić bez problemu musiałem co chwilę się bawić. Zrobiłem w nocy pull requesta z kawałkiem tłumaczenia które oczywiście zignorowaliście i znów muszę poprawiać żeby dało się go scalić bez kombinowania i większej wiedzy.

Reasumując: jeżeli chcecie żeby ktokolwiek Wam pomagał (bo tak działają projekty Open Source jak ten) to musicie też słuchać innych. Propozycja żeby nie zaśmiecać mastera przez x godzin commitami "Alpha 14" jest jak najbardziej zrozumiała. Poczytajcie trochę o git, jak zrobić sobie repo na własnym komputerze, zedytujcie tam 20 plików i wgrajcie to jako jeden commit. Wtedy będziemy rozmawiać o dorobku i byciu profesjonalnym.

**Comment by Fejm** [comment]
Chciałbym dodać poza tym że bardzo szanuję waszą pracę, to co do tej pory zrobiliście jest bardzo pomocne dla wielu naszych rodaków. Natomiast jeśli mam się wypowiadać na temat używania gita to sorry ale.. :)

**Comment by Nalthe** [comment]
Nie rozumiesz też jednego - na masterze powinien pracować ktoś, kto jednak zna minimum język. Mi chodzi tylko o to. Nie mówię o angielskim, bo ten zna obecnie każdy dzieciak z podstawówki. Ale wybacz, nie pozwolę, żeby osoba, która wstawia "ważywa" kazała mi pracować na gałęzi i wysyłać jej pullrequesty XD Przecież to jest śmieszne. Na GitHubie pracowałam i szczerze - tylko z Wami mam problem. 

Na własnym komputerze obecnie tłumaczyć nie mogę, bo to komputer firmowy. Przykro mi. Co do zaśmiecania Alpha 14 - to nie ja dodałam 50 commitów "I'm  back" xD

**Comment by Fejm** [comment]
Zerknie ktoś na pull request'a? :)

**Comment by MisterMareoPL** [comment]
Siema sorki ze sie wbijam ale robimy cos wspolnie mozemy uszanowacsiebie i
nie obrazac sie ? Co do niemieckiego... ja go nie znam a uczylem sie 3 lata
wiec i jest dla mnie nie przydatny... Nika " Nie mówię o angielskim, bo ten
zna obecnie każdy dzieciak z podstawówki" tu sie mylisz ja ukoniczylem gim
w tym roku i stwierdzam ze poziom szkolnej edukacji jest strasznie
podstawowy za duzo teori malo praktyki :)

2016-08-07 23:41 GMT+02:00 Mateusz Filipczak <notifications@github.com>:

**Comment by Nalthe** [comment]
My robimy wspólnie już od jakiegoś czasu, więc... Dla mnie to nie jest żaden problem, dopóki ktoś nie ma przerostu ego ;> 
Nie mówiłam o dzieciach, którym się nie chce robić nic, tylko które faktycznie tę szkołę kończą. Mój brat ma obecnie 9 lat, a jest w stanie grać po angielsku  ze swoimi kolegami bez większych problemów. Zresztą, co to ma do rzeczy. Tłumaczenie niemieckie jest lepsze - kropka. Warto z niego korzystać, to nie jest problem, gdy chodzi o jedno słowo, a często takie były.

**Comment by MisterMareoPL** [comment]
Dobra opisze ci to tak mam uzyc tlumaczenia niemieckiego ok otwieram patrze
i co ? NIE znam niemieckiego bum ! i tak jak to wspomnialas jest lepsze i
skorzystam zniego takk takk

W dniu 13 sierpnia 2016 16:51 użytkownik Nika <notifications@github.com>
napisał:

**Comment by Nalthe** [comment]
Czytanie ze zrozumieniem boli? Przecież piszę, że jest pomocne zwłaszcza jeśli chodzi o pojedyncze słowa. Ok, możesz nie rozumieć zdania, ale nie przesadzaj, że JEDNEGO słowa nie zrozumiesz. A właśnie takie w większości były źle przetłumaczone.

**Comment by Fejm** [comment]
Proponuję zamknąć ten issue. Ja mam 23 lata, jestem programistą, skończyłem technikum elektroniczne,  studiowałem informatykę i jakoś nie czuje się urażony gdy ktoś znajdzie w moim tłumaczeniu literówkę bądź błąd. Nie wszystko też tłumaczymy dosłownie bo się nie da. Natomiast są rzeczy o których nie wolno zapominać jak np. Nie stawiamy spacji przed znakiem zapytania, wykrzykniknikiem czy innym znakiem interpunkcyjnym. Darujmy kłótnie już. Zróbcie sobie forka, pracujcie na nim a potem kliknijcie zielony przycisk od pull requesta. Będzie można przejrzeć wasze zmiany i je dodać bez spin. Takie jest moje zdanie. Miłego wieczoru.

P.s. Będę nie aktywny 11 dni, wyjeżdżam za granicę :)
