### ISSUE TITLE
Spacer

### ISSUE THREAD

**Issue by Nalthe** [Ludeon/RimWorld-Polish#24]
Hi'o. Tak pomijając dawne waśnie etc. Co robimy ze spacerami? Dla przypomnienia - jedna z frakcji. Obecnie przetłumaczona jako "kosmonauta", "kosmonauci". IMHO jednak to mało oddaje jej charakter - kosmonauta to po prostu osoba odbywająca loty kosmiczne. Jednak gramy poniekąd już będąc w kosmosie i nie na własnej planecie, sami de facto też taki lot odbyliśmy, no i "kosmonauta" kojarzy się raczej z celami naukowymi. Może więc postawimy tutaj na nieco kreatywności i zmienimy tę nazwę na nieco bardziej oddającą jej charakter? Myślałam nad "obcymi", jednak za bardzo będą kojarzyć się z UFO, coś w stylu "uchodźców" odpada ze względu na ostatnie sytuacje polityczne xD Coś w stylu "wędrujących" etc.? Jakieś pomysły? Czy po prostu odpuszczamy?

**Comment by Nalthe** [comment]
Z tego, co przejrzałam, większość innych tłumaczeń poszła w kierunku "przestrzennych podróżnych", "kosmicznych podróżnych" etc.

**Comment by Fejm** [comment]
Kosmiczny podróżnik?

**Comment by Fejm** [comment]
P.s. Dzięki że poprawiasz moje literówki. Siedziałem nad tym całą noc i pod koniec, gdy pisałem spolszczenia chyba już ślepy się zrobiłem na te literówki. Większość i tak dało radę przekleić ze starych tłumaczeń - ich nie sprawdzałem bo uznałem że są dobre.

**Comment by Nalthe** [comment]
Meh, taka robota, wkurzają mnie xD Kosmiczny podróżnik IMHO ok, tylko trzeba będzie sprawdzić, czy nigdzie nie wychodzi poza ramki w grze.
