### ISSUE TITLE
Jest coś do zrobienia?

### ISSUE THREAD

**Issue by Fejm** [Ludeon/RimWorld-Polish#34]
Aktualnie mam chwilę czasu i zastanawiam się czy jest coś do zrobienia? I skąd bierzecie tagi z nowego update? :)

**Comment by Nalthe** [comment]
Błędy w tłumaczeniu D: Z jakiegoś powodu nie działa Keyed/Misc_Gameplay.xml - możliwe, że wynika to z niektórych Defów, ale z usuwaniem nadmiarowych wolałam poczekać, aż opublikuje je Sakuukuli, jednak chyba trzeba będzie to robić na własną rękę, bo coś mu się nie śpieszy.

Jak otworzysz Rima, wywala całą konsolę błędów, więc no, śmiało xDD 

Tagi:
- Defy: https://ludeon.com/forums/index.php?topic=24936.0
- Keyed, Strings: szukasz swojego folderu Rima, u mnie to C:\Program Files (x86)\Steam\steamapps\common\RimWorld\Mods\Core\Languages\English (w tym folderze da się znaleźć też Defy, ale z tych nie korzystamy - są tam nadmiarowe pliki etc.)

**Comment by piotrulos** [comment]
Błąd jest prosty, bo zamykany jest tag </AreaDefault**z**Label> zamiast </AreaDefaultLabel> 
Przecież nawet konsola wskazuje linijkę gdzie jest błąd.

Przeglądam teraz całe tłumaczenie porównując z oryginalnymi plikami. Ogólnie sporo jest głupot w tagach xml, np. otwierany jest tag <Panther.coś tam> a zamykany </Squirrel.coś.tam> i jak to ma nie wywalać błędów?
