### ISSUE TITLE
Shiv - brzytwa

### ISSUE THREAD

**Issue by ArturLange** [Ludeon/RimWorld-Polish#41]
Witajcie.
Zauważyłem że `shiv` zostało przetłumaczone jako `brzytwa` i chciałbym poruszyć ten temat.
Nie do końca mi się to podoba, `brzytwa` sugeruje raczej że jest to coś czym się należy golić.
Moim zdaniem bardziej pasuje z gwary więziennej `kosa` lub `kosior`. Niestety `kosa` też nie jest jednoznaczne, więc proponowałbym `kosior`.
Zapraszam do dyskusji.

**Comment by Nalthe** [comment]
Możesz podać, w jakim pliku? Czy chodzi o stringi?

**Comment by kerberois** [comment]
Może po prostu "ostrze"?

Dnia 2 stycznia 2017 12:23:28 CET, Artur Lange <notifications@github.com> napisał(a):
>Witajcie.
>Zauważyłem że `shiv` zostało przetłumaczone jako `brzytwa` i chciałbym
>poruszyć ten temat.
>Nie do końca mi się to podoba, `brzytwa` sugeruje raczej że jest to coś
>czym się należy golić.
>Moim zdaniem bardziej pasuje z gwary więziennej `kosa` lub `kosior`.
>Niestety `kosa` też nie jest jednoznaczne, więc proponowałbym `kosior`.
>Zapraszam do dyskusji.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Ludeon/RimWorld-Polish/issues/41

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by maxdyner** [comment]
Oddaję głos za ostrze!

**Comment by Nalthe** [comment]
Chwila, czekajcie. Najpierw kontekst xD Dlatego proszę o to,  w jakim pliku się to znajduje.

**Comment by Nalthe** [comment]
Jeśli się nie mylę, chodzi o plik DefInjected\ThingDef\Weapons_Melee.xml, tak? (Wybacz, dopiero teraz miałam dostęp do komputera). Jak dla mnie, ostrze będzie jak najbardziej w porządku i adekwatne do wyglądu (http://rimworldwiki.com/wiki/Shiv i w rzeczywistości: https://en.wikipedia.org/wiki/Shiv_(weapon)) - kosa moim zdaniem kojarzy się w Polsce z większym narzędziem i mniej wprawnego gracza wprowadzi w błąd. 
Ewentualnie możemy poszukać nazwy bardziej związanej po prostu z definicyjnym nożem, żeby uniknąć ogólnikowego ostrza.

**Comment by ArturLange** [comment]
Brzytwę znalazłem w 
`DefInjected/ThingDef/Weapons_Melee.xml`
`DefInjected/RecipeDef/Recipes_Add.xml`
`Strings/Words/Nouns/Weapons.txt`
oraz
`Podręczny słownik.md`

**Comment by Nalthe** [comment]
W defach zmienię, w stringach - jeśli dobrze pamiętam (upewnię się po 14) - ostrze już występuje, dublowanie nie ma sensu, bo stringi służą do generowania różnego rodzaju zdań w grze niemających większego wpływu na rozgrywkę. No i tam jest przetłumaczone bodajże jako prowizoryczne ostrze. Ale co do stringów upewnię się po tej 14.

**Comment by Nalthe** [comment]
Ok. Miało być po 14, pęknięta opona pokrzyżowała plany, wybaczcie.
W defach zmienione, jeśli chcecie od razu widoczną zmianę w grze - oczywiście trzeba wgrać tłumaczenie.

W stringach jest brzytwa, ale jako tłumaczenie "razor", więc w tym wypadku nie widzę powodu, by to zmieniać. Samo shiv zostało jednak **tymczasowo** przetłumaczone jako "prowizoryczne ostrze" - i wymaga zmiany, więc przy okazji tego tematu możemy poruszyć tę kwestię. "Ostrze" odpada - nie powinno się powtarzać z pozostałymi stringami w tym pliku (Strings/Words/Nouns/Weapons.txt). Jeśli jednak ktoś ma pomysł na nazwę dla prowizorycznego narzędzia - śmiało, będzie to bardzo pomocne. Powinno to być raczej jedno słowo. Moim zdaniem nie powinno jednak być zbyt wymyślne, żeby zrozumiał je przeciętny gracz - jeśli macie jakieś pomysły, to rzucajcie, mi nic na razie nie przychodzi do głowy.

**Comment by kerberois** [comment]
Re: [Ludeon/RimWorld-Polish] Shiv - brzytwa (#41)


https://en.wikipedia.org/wiki/Shiv_(weapon)

Wygląda to po prostu na prowizoryczny nóż.


----------------------------------------------- 
Pozdrawiam - Mariusz Litwińczuk    Odpisz na:litwinczuk@poczta.fm
Gadu-Gadu: 1044091
Skype: mlitwinczuk
Tel: 0-668-118-027
http://blog.lordswm.org --- http://lordswm.org

 Myśl dnia:
  Tak to w życiu bywa.. raz na wozie raz pod wodą...

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-


Witaj Nika, w Twoim liście z dnia (03.01.2017 - 16:26) piszesz:




Ok. Miało być po 14, pęknięta opona pokrzyżowała plany, wybaczcie.
W defach zmienione, jeśli chcecie od razu widoczną zmianę w grze - oczywiście trzeba wgrać tłumaczenie.
W stringach jest brzytwa, ale jako tłumaczenie "razor", więc w tym wypadku nie widzę powodu, by to zmieniać. Samo shiv zostało jednak tymczasowo przetłumaczone jako "prowizoryczne ostrze" - i wymaga zmiany, więc przy okazji tego tematu możemy poruszyć tę kwestię. "Ostrze" odpada - nie powinno się powtarzać z pozostałymi stringami w tym pliku (Strings/Words/Nouns/Weapons.txt). Jeśli jednak ktoś ma pomysł na nazwę dla prowizorycznego narzędzia - śmiało, będzie to bardzo pomocne. Powinno to być raczej jedno słowo. Moim zdaniem nie powinno jednak być zbyt wymyślne, żeby zrozumiał je przeciętny gracz - jeśli macie jakieś pomysły, to rzucajcie, mi nic na razie nie przychodzi do głowy.

**Comment by Nalthe** [comment]
Jak pisałam wyżej, lepsze byłoby jedno słowo. Zdarzyło mi się widzieć Tomahawk jako pseudonim w grze - obawiam się, że przydomek "prowizoryczne ostrze" będzie brzmiał niezbyt ciekawie. No i dochodzi kwestia odmiany - łatwiej operować jednym słowem w zdaniach niż rzeczownikiem + przymiotnikiem.

**Comment by kerberois** [comment]
Re: [Ludeon/RimWorld-Polish] Shiv - brzytwa (#41)


Oryginał to był jakiś prowizoryczny nóż.

Inny synonim tego słowa:

głownia - bardzo zbliżone do oryginału w wyglądzia

https://www.google.pl/search?q=głownia&client=opera&hs=TmX&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiDobP54qbRAhWI1iwKHWeiBw8Q_AUICCgB&biw=1302&bih=1626&dpr=1.25 

"Głownia, brzeszczot, (z niem.) klinga, (staropol.) żelazo – jedna z dwu podstawowych części każdej broni białej, drugą częścią jest rękojeść. Głownia jest zasadniczą (główną – stąd etymologia), roboczą częścią broni tego typu. Służy do zadawania i odparowywania ciosów "








----------------------------------------------- 
Pozdrawiam - Mariusz Litwińczuk    Odpisz na:litwinczuk@poczta.fm
Gadu-Gadu: 1044091
Skype: mlitwinczuk
Tel: 0-668-118-027
http://blog.lordswm.org --- http://lordswm.org

 Myśl dnia:
  Będę księdzem. Jak mój ojciec.

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-


Witaj Nika, w Twoim liście z dnia (03.01.2017 - 20:32) piszesz:




Jak pisałam wyżej, lepsze byłoby jedno słowo. Zdarzyło mi się widzieć Tomahawk jako pseudonim w grze - obawiam się, że przydomek "prowizoryczne ostrze" będzie brzmiał niezbyt ciekawie. No i dochodzi kwestia odmiany - łatwiej operować jednym słowem w zdaniach niż rzeczownikiem + przymiotnikiem.

**Comment by maxdyner** [comment]
A jak by tak nożyk? albo coś prostego w okolicy znaczenia jakiego szukamy?
No bo nóż jest to niech będzie nożyk (może).
Moim zdaniem nie ma się co tak rozwodzić nad tym ani ten element nie ma większego znaczenia dla rozgrywki ani nie piszemy o tym pracy doktorskiej. Można tam pisać coś blisko znacznego i to w zupełności wystarczy bo chyba chodzi o fajną rozrywkę i raczej tłumaczenie shiv jako nożyk czy podobne komuś immersji nie rozwali ;)

**Comment by Nalthe** [comment]
Wiesz, pracy doktorskiej może i nie piszemy, ale też nie lubię robić rzeczy na odwal się. Inna kwestia, że to moje zboczenie zawodowe - jako tekstologowi zależy mi na oddaniu tego, co chciał oddać autor. xD

**Comment by ArturLange** [comment]
Dlatego też bardzo polecam jednak słowo `kosior`, bo to jest chyba jedyne wierne tłumaczenie, pochodzi z gwary więziennej.
Shiv to właśnie taki nóż wykonany z tego co akurat jest pod ręką, najczęściej w więzieniu, 
> slang term for any sharp or pointed implement used as a knife-like weapon

wg wikipedii

Zresztą myślę, że w grze gdzie gra się z otwartą w tle wiki gry problemem nie jest sprawdzić sobie co to znaczy (bo pewnie nie każdy wie)

**Comment by maxdyner** [comment]
Co do "kosiora" to niestety nie wszyscy znają znaczenie tego słowa a myślę że tłumaczenie powinno być przystępne. Zawsze możemy zacząć używać "specjalistycznej" mowy ale ciężko będzie to potem czytać  (znam kilka osób po odsiadce) w okolicach Częstochowy mówimy na taki nóż kosa i tyle kosior raczej w tym rejonie nie przejdzie to tak jak wychodzenie na dwór i na pole trzeba tłumaczyć jako wychodzenie na zewnątrz i tyle. (ale co ja tam wiem ;) )

**Comment by Nalthe** [comment]
Tymczasowo zmieniłam na kosior - niestety kosa jest już zajęta i jeśli chodzi o przystępność, też bym ją preferowała, no ale myślę, że każdy wpadnie na to, że "kosior" to jakiś tam rodzaj broni. xD

**Comment by hapalupa** [comment]
Witajcie, jeżeli mogę wtrącić swoje pięć groszy, to chciał bym zaznaczyć że słowo "kosior" jest bardzo regionalne, a w słowniku figuruje jako:

> [kosior](http://sjp.pwn.pl/doroszewski/kosior;5442727.html): rodzaj pogrzebacza, deszczułka osadzona na długim kiju, służąca do wygarniania węgli z pieca chlebowego

 Więc w mojej opinii jeżeli chcecie używać slangu to przynajmniej używajcie takiego który znajduje sie w slowniku jak np. majcher:

> [majcher](http://sjp.pwn.pl/doroszewski/majcher;5448838.html): nóż używany w bójkach (z jezyka złodziejskiego)

Osobiście podoba mi się pomysł wyżej wymieniony przez @kerberois, tylko że zamiast _"głownia"_ (która raczej oznacza część tnącą broni białej) użył bym nazwy _"brzeszczot"_. Jest to nazwa ogólna równie dobrze mogąca oznaczać ostrze broni jak i samą broń jak w tym przykładzie ze słownika pwn: [Z uśmiechem spoglądał na jego potężny kord, nie mniejszy od dwuręcznych niemieckich brzeszczotów.](http://sjp.pwn.pl/doroszewski/brzeszczot;5415038.html). 

Jest to poniekąd dwuznaczne więc pozostawiam wam to do oceny. Ewentualnie jeżeli chcecie użyć nazwy powszechnie zrozumiałej przez wszystkich bez użycia słownika dlaczego nie użyjecie poprostu _"sztylet"_. Jest to wprawdzie nazwa dla broni obosiecznej gdzie w rimworld jest użyty sprite z broni jednosiecznej ale nie sądze czy ma to jakąś większą różnicę, bardziej może być problematyczny fakt że raczej nie jest to broń improwizowana.

**Comment by Nalthe** [comment]
Szczerze mówiąc, brzeszczot za bardzo kojarzy się z narzędziem, dlatego moim zdaniem odpada. 

Slang znajdujący się w słowniku? Nie każde pojęcie slangowe znajduje się w słowniku, ponieważ autor nie musi być go świadomy - to raz. Dwa - słowniki pochodzą głównie z lat 80 i są lekko aktualizowane każdego roku, jednak bardzo rzadko o słowa ze slangu. Co chcę powiedzieć - wielu słów slangowych nie znajdziesz w słowniku, bo zwyczajnie nie są o nie aktualizowane. Druga kwestia - slang jest zmienny, dlatego nie zawsze trafia on do słownika - słowniki zapisują raczej trwałe pojęcia. 

Nie użyjemy "sztylet", ponieważ jest już ta nazwa wykorzystana. I akurat tutaj możemy użyć slangu, bo to stringi.

**Comment by maxdyner** [comment]
Znam majcher i w okolicy Częstochowy przejdzie :) to może majcher chyba że wam to nieznane.

**Comment by Kunegard** [comment]
Zdaje mi się, że w Rima gra nie tylko okolica Częstochowy. Ale tylko domniemam.

**Comment by hapalupa** [comment]
@Nalthe no cóż, samo słowo _"shiv"_ znajduje się w słowniku, również _"majcher"_  znajduje się w słowniku. Słowo _"kosior"_ znajduje się w słowniku jako pogrzebacz. Osobiście nigdy nie spotkałem się z użyciem tego słowa do nazwania noża. Zapytałem też znajomych ale nikt nie spotkał się z tym słowem, z drugiej strony wszyscy byli w stanie stwierdzić że jest to słowo pochodne od kosy. Jeden znajomy zgadywał że może to być część tnąca kosy. :)

Wydaje mi się poprostu że już lepszym wyborem była brzytwa. rozumiem że jest to słowo dwuznaczne ale przynajmniej każdy rozumie że jest to mały, tnący, przedmiot przypominający w budowie nóż, a nie np. ostrze kosy. W slangu może również oznaczać ostry nóż, podczas gdy _"kosior"_ brzmi jak słowo wymyślone na potrzeby tego tłumaczenia żeby nie użyć, również dwuznacznego słowa, _"kosa"_.

**Comment by Nalthe** [comment]
Ale porównujesz słowo angielskie? Angielskie słowniki tworzy się inaczej, w Polsce jest niewielu redaktorów, którzy się tego podejmuje - a uwierz, coś o tym wiem, bo jestem redaktorem z zawodu xD Nie napisałam nigdzie, że "kosior" jest idealny, tylko że WSTĘPNIE go wstawiam - ale jest bardziej domyślny niż "majcher" dla przeciętnego gracza (bo przykro mi, ale ja nie znam żadnego z tych słów w kontekście ostrzy - ale słysząc je gdziekolwiek, jestem w stanie się domyślić, że kosior jest z nimi związany, a do majchra już bym nie miała takich podejrzeń). 

Brzytwa jest już użyta. Toć już to pisałam wyżej.

**Comment by Nalthe** [comment]
Żeby nie było wątpliwości - do tej pory użyte słowa:
```
nóż
ostrze
bat
piła
dzida
maczuga
kastet
kosior [to chcemy zmienić]
sztylet
rękawica
miecz
brzytwa
kordelas
rapier
szabla
topór
tomahawk
młotek
toporek
młot dwuręczny
kosa
pięść
rękawica
gladius
kordelas
szabla
rapier
wielki miecz
sierp
pika
kopia
buława

rzutka
strzała
broń palna
kusza
pistolet
karabin
działo
strzelba
bomba
bomba atomowa 
pocisk
rakieta
mina
```

**Comment by Nalthe** [comment]
I proszę - nie róbmy niepotrzebnych dyskusji na temat jednego słowa. Szukamy najlepszego rozwiązania, a nie przekonujemy się, że coś nam się podoba. W najlepszej wersji ma się podobać wszystkim - do tego dążymy, po to jest ta dyskusja, nawet jeśli w teorii nie da się znaleźć czegoś takiego. A jeśli nie "podobać" - to być zrozumiałe, domyślne. No i przypominam, że to stringi - a nie nazwa przedmiotu w grze. Stringi służą do budowy zdań (np. sztuka), niektórych historii, czasami jako przydomki - i w tym kontekście muszą być domyślne, nakreślać graczowi pewne **zrozumiałe** obrazy w wyobraźni.

**Comment by maxdyner** [comment]
No tak ale dla mnie też " "kosior" brzmi jak słowo wymyślone na potrzeby tego tłumaczenia" zgodnie z wypowiedzą hapalupa.
A jako okolice Częstochowy mam na myśli północną część śląska i okolice bo każdy rejon ma swoje słownictwo. Kunegard jak pisałem wcześniej można tłumaczyć po "swojemu" np: "wychodzę na pole" al poza Krakowem i na wschód od niego się nie używa takiego określenia i w reszcie Polski będzie taki termin gryzł w oczy. Mam nadzieję że jakoś polubownie to załatwimy.

**Comment by Kunegard** [comment]
Co znaczył dla Ciebie "kosior" przed sprawdzeniem terminu w słowniku? Jakie nanosił skojarzenia?

**Comment by maxdyner** [comment]
Nie nosił jak pisałem " "kosior" brzmi jak słowo wymyślone na potrzeby tego tłumaczenia" i na dodatek nie kojarzy mi się z omawianym przedmiotem.

**Comment by hapalupa** [comment]
Z tego co widzę to _"sledgehammer"_ jest przetłumaczony na _"młot dwuręczny"_, tak samo _"claymore"_ został przetłumaczony na _"wielki miecz"_, więc jeżeli przymiotnik z rzeczownikiem jest problematyczny w stringach należałoby to też zmienić. Proponuje młot oraz pałasz w odpowiedniej kolejności.

Co do _"shiv"_ to proponuje słowo nożyk które może nie jest najwierniejszym tłumaczeniem ale na pewno jest zrozumiałe przez wszystkich.

Alternatywnie można zamienić _"razor"_ na _żyletka_ lub _żyleta_, a _"shiv"_ na _brzytwę_.

**Comment by kerberois** [comment]
Re: [Ludeon/RimWorld-Polish] Shiv - brzytwa (#41)



Shiv:
https://en.wikipedia.org/wiki/Shiv 
https://en.wikipedia.org/wiki/Shiv_(weapon)

= to po prostu wygląda jak nożyk.
Ostrze jest także nazywane jako "głownia"

https://pl.wikipedia.org/wiki/Głownia 
Głownia, brzeszczot, (z niem.) klinga, (staropol.) żelazo – jedna z dwu podstawowych części każdej broni białej, drugą częścią jest rękojeść. 

https://www.google.pl/search?q=głownia&client=opera&hs=6FP&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi0icyUyMHRAhWrFZoKHRetAUgQ_AUICCgB&biw=921&bih=1016 


Obrazki pokazują po prostu nożyk (czy też ostrze które należy osadzić w rękojeści.
Wyszukanie "shiv weapon" czy też po polsku "głownia" po ograzkach google daje praktycznie identyczne wyniki.

Wstawmy nożyk albo głownia - tu się nie ma nad czym rozwodzić.





----------------------------------------------- 
Pozdrawiam - Mariusz Litwińczuk    Odpisz na:litwinczuk@poczta.fm
Gadu-Gadu: 1044091
Skype: mlitwinczuk
Tel: 0-668-118-027
http://blog.hakimodo.pl --- http://hakimodo.pl

 Myśl dnia:
  Dla niejednego mężczyzny żona stanowi lepszą połowę jego gorszego bytu.

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-


Witaj Pawel, w Twoim liście z dnia (14.01.2017 - 12:19) piszesz:




Z tego co widzę to "sledgehammer" jest przetłumaczony na "młot dwuręczny", tak samo "claymore" został przetłumaczony na "wielki miecz", więc jeżeli przymiotnik z rzeczownikiem jest problematyczny w stringach należałoby to też zmienić. Proponuje młot oraz pałasz w odpowiedniej kolejności.
Co do "shiv" to proponuje słowo nożyk które może nie jest najwierniejszym tłumaczeniem ale na pewno jest zrozumiałe przez wszystkich.
Alternatywnie można zamienić "razor" na żyletka lub żyleta, a "shiv" na brzytwę.
