### ISSUE TITLE
Status tłumaczeń dla A16?

### ISSUE THREAD

**Issue by ests** [Ludeon/RimWorld-Polish#43]
Podczas gry w aktualną wersję (A16), zauważyłem, że miejscami brakuje kilku linijek tłumaczeń (np. "Deteriorating due to beeing unroofed"), inne tłumaczenia są połamane (jakby przeszły tylko przez translator). Czy ktoś wie dlaczego tak jest i czy potrzebna jest jakaś pomoc?

**Comment by Nalthe** [comment]
Nie tłumaczymy przy użyciu translatora. Nie wszystkie pliki są już dostępne do tłumaczenia. Część zdań jest generowana automatycznie przy użyciu pojedynczych słów (np. przy opisach sztuki). Producent gry nie zapewnił jeszcze możliwości dodania pełnej gramatyki i np. odmiany, również są miejsca, których na razie w ogóle nie da się przetłumaczyć - stąd błędy, w końcu gra znajduje się nadal w alfie.
Dodatkowo znajdujemy się na granicy patchów, wszystko zostanie uzupełnione, gdy tylko wyjdzie A17 - przynajmniej na tyle, na ile będzie mogło być uzupełnione.

**Comment by ests** [comment]
Nie podejrzewałem nawet, że ktoś to tłumaczy przy pomocy translatora - jedynie jak to wygląda. Ale teraz rozumiem. Wracając do drugiej części pytania - czy w tej chwili można jakoś pomóc, i.e. jest coś do zrobienia?

**Comment by Nalthe** [comment]
W tym momencie nie ma nic - czekamy na A17. Tak jeszcze co do frazy, którą podałeś - w tłumaczeniu jest ona zrobiona, na pewno nie masz wgranej najnowszej wersji. (Instrukcja, jak to zrobić: http://rimworldpolska.pl/jak-wgrac-tlumaczenie).
I tak na przyszłość - stan tłumaczenia aktualizujemy na bieżąco tutaj: http://rimworldpolska.pl/faq

**Comment by ests** [comment]
Aj, sorki, zaglądałem na stronę ale widać niezbyt umiejętnie bo nie dotarłem do FAQ. Dziękuję za waszą pracę i pozdrawiam!

**Comment by Nalthe** [comment]
Dzięki, postaramy się więc umieścić to w bardziej widoczny sposób, żeby nie było z tym problemów ^^ Jak po A17 będziesz zainteresowany pomocą, to wpadnij tu.
