### ISSUE TITLE
Joywire

### ISSUE THREAD

**Issue by westwinnd** [Ludeon/RimWorld-Polish#47]
śmiecho-drut, druto-ciesz, ciesz-kabel, druto-śmiech.

-- nazwa to zlepek prostych słów joy+wire sprawia, że informację o obiekcie zrozumieją nawet średniowieczni nędzarze nie ogarniający meandrów neurochirurgii (kabel szczęścia do móżgu!)
-- obecność w sklepach piratów (piraci poganiający elektroników ślęczących nad trawionymi płytkami scalonymi, żeby później opychać szajs w indiańskich wioskach), 
-- możliwość uzależnienia od implantu, 
-- obecność wire w nazwie (technologia daleko mniej zaawansowana od bioniki sugeruje, że możnaby pokusić się o neologizm, opierając się na cyberpunkowych realiach nazw narkotyków od zlepków prostych słów.

Yes? No?

**Comment by Nalthe** [comment]
Jaka jest Twoja konkretna propozycja? Dywagacji jest wiele, zostawianie angielskich słówek jest zwyczajnie niefajne, zwłaszcza jeśli dane słowo nie istnieje i nie jest szeroko przyjęte w kulturze ("joywire" to nie "weekend").

**Comment by westwinnd** [comment]
Risercz:
(1)    https://www.reddit.com/r/RimWorld/comments/38i7jf/joywire/

Dowiadujemy się tutaj obviously, że Tynan pracuje nad mechaniką i nie może poświęcić dużo czasu na precyzowanie, dokładnie co czym jest. Ale. Wiemy, że uzależnieni od joywire nazywają się wireheads.
Pod powyższym linkiem ktoś zasugerował, że Tynan mógł inspirować się prozą Larry'ego Nivena - Ringworld (Pierścień). 

(2)   http://larryniven.wikia.com/wiki/Wirehead

Lektura "Pierścienia" daje nam opis urządzenia, który z grubsza pasuje do intuicyjnego wyobrażenia (jest to dość wiekowe sci-fi, więc i idea tasp, naszego kandydata na joywire'a, już od dawna się zadomowiła w kulturze).
oczywiście, pojęcie pojawia się również w innych książkach:

(3)   https://en.wikipedia.org/wiki/Wirehead_%28science_fiction%29
Ponadto wiemy, że urządzenie jest stosunkowo niedrogie ( 2x TV), oraz, że ich twórcy to w oryginale Joywire Artists.

Powyższe zbierając, kierując się założeniami:
słowo nie powinno brzmieć zbytnio naukowo - powinno być jak uliczna nazwa narkotyku, zrozumiała dla  człowieka z każdej epoki technicznej - bowiem wszyscy oni spotykają się na jakimś etapie życia w rimworld, gdzie migrują, chcą zamieszkać w glitter, spotykają się z podróżą kosmiczną, światami tranzytowymi, albo lądują na rimie, gdzie w wiosce 10km od crashsite w ciemnej uliczce dorwie ich dealer, i wciśnie któremuś z nich "szczęście Twojego życia i oderwanie od rzeczywistości".  Możemy się domyślać, że pierwsze próby tłumaczenia klientowi (czy ze średniowiecza, czy z indworld), co to za urządzenie i jak działa, będą miały szanse stać się obiegową nazwą przedmiotu.

Wysuwam takie słowo-twory:

1.kabel-frajd, lub kabelfrajd. 

(wyobraźmy sobie dealera-elektronika, wykonującego ruchy falujące ręką przy wymowie sylab tego słowa, przy próbie opchnięcia urządzenia osobnikowi, mówiącego: "joł, rimie!, to jest ka-bel-fraaaaajd, mózgowy over-drive! frajda na zawsze, tony frajdy! za darmo! do końca życia, stary.)
+ ładnie brzmi, rymuje się z overdive :P
+
2. drut-frajd, druto-frajd (lub drut-frajda)  (cyberpunkowy background z grubsza jak wyżej)
+ do tego: homofoniczny z joywire.
+ nieco kojarzy się z gwarą śląską, tak jak słowa wichajster, fajrant, szlus.

3. frenektroda. frenezja+elektroda.  
+ bardziej naukowy, nie spełnia wyżej rozpisanych założeń, ale jest bardzo precyzyjny w przekazywaniu informacji o przedmiocie.

Inne, które na wstępie opisałem, ale po riserczu, piętnuję:

4. śmiech-drut....  śmiechdruty-andrutyyy. neeein. takie 2/5.
5. błogo-drut.
6. druto-ciech. (zbyt swojskie, słowiańskie, jak Wojciech, Radociech, Miłomir).

**Comment by Nalthe** [comment]
Ale dlaczego "frajd"...? Szczerze, wszystkie te złożenia brzmią zwyczajnie... śmiesznie. A co gorsza - niczego nie sugerują. Pamiętajmy, że tłumaczenie ma być przede wszystkim zrozumiałe dla gracza. Żadna z tych nazw kompletnie nie sugeruje, że jest to coś, co jakkolwiek wpływa na mózg.

**Comment by westwinnd** [comment]
Frajd od frajdy. W frajdzie jest rajd! :)))) Frajda była słowem popularnym w latach 80', również w subkulturach. Idea urządzenia pojawiła się w latach 70' w science-fiction, cyberpunku. Nasz Joywire jest bardzo uzależniający - nietrudno sobie wyobrazić, że jest nielegalny (na glitterworld choćby) - więc pewnie produkcja i serwis takich urządzeń zszedł do podziemia. Stąd starałem się, żeby brzmiało "nielegalnie", ulicznie, slangowo, cyberpunkowo, itd. 
Określenie Joywire również nie sugeruje, że chodzi o neuroimplant.... a może trochę... ("okablowanie szczęścia").
mhmmm.....

**Comment by ByJacob** [comment]
Zamykam z powodu że wątek jest dość stary
