### ISSUE TITLE
Sekcja Autorzy!!!

### ISSUE THREAD

**Issue by maxdyner** [Ludeon/RimWorld-Polish#48]
Chciałem podziękować pięknie za wdupiemiejstwo ludzi którzy poświęcili kupę swojego czasu dla tłumaczenia i usunięcie ich z sekcji autorzy.  Piękne podziękowanie od klasy rządzącej ;) jak widać udzieliło wam się dzielenie ludzi na lepszych i gorszych. I tak jestem bardzo nie zadowolony bo nie lubię być traktowany jak odpad.

**Comment by Nalthe** [comment]
To nie jest podział na "lepszych" i "gorszych". Poprzednie tłumaczenie zostało praktycznie  w całości usunięte i zrobione od nowa z powodu wielu błędów w translatoryce (nie mówię tu o błędach językowych). Nie bez powodu mam tyle usuniętych linijek - i nie bez powodu tyle dodanych. W obecnym tłumaczeniu uczestniczyły osoby, które są widoczne w plikach.

Jest to również odpowiedź na chyba największy polski fanpage Rima na FB: https://www.facebook.com/pg/RimWorldPoland/about/?ref=page_internal - tutaj wymieniona jest tylko grupa Hoffmana, która już w ogóle zrobiła tu chyba najmniej (i nadal robi najmniej, a prośby o dodanie innych skutkują dokładnie niczym).

**Comment by maxdyner** [comment]
A to ok jak ktoś jedzie na twojej pracy i przypisuje ją sobie to i ty robisz to samo tak?
Jak ciebie okradną to ty też kradnij.
Zacznij spamować im na tablicy że nie oni robią tłumaczenie, może napisz im masę komentarzy. Walnij jakiś artykuł o tym jak kradną twoją pracę i wrzuć na wykop.pl a w końcu ich sprawiedliwość dopadnie.

**Comment by Nalthe** [comment]
W pliku README są wymienieni wszyscy, którzy wcześniej pracowali nad projektem.

**Comment by hapalupa** [comment]
Pół prawdy i zranione ego...
Nie ma znaczenia czy tłumaczenie było "praktycznie w całości usunięte i zrobione od nowa" jeżeli ktoś pracował nad tłumaczeniem na początku i poświęcił mu czas, tak samo przyczynił się powstaniu tego tłumaczenia. Powiedzmy że jutro przestaniesz się zajmować tym tłumaczeniem, wrócisz za rok a ktoś ci powie że gra się tak zmieniała że musiał wszystko co ty zrobiłaś zmienić. Jakaś bzdura. Jeżeli pracowałeś na podstawie czyjegoś tłumaczenie ta osoba musi być uwzględniona w creditsach. 
Co do strony na Facebooku to wyglada ze do całkiem niedawna była całkowicie opuszczona. Nigdzie na samej stronie też nie znalazłem linku do gita, jest tam link do ich starego tłumaczenia na one drive i dwa do ich postów na forum ludeon.com, Z forum ludeon oczywiscie link jest do githuba ale wyglada ze sam post poprostu nie był edytowany od alpha 4. Dlatego jeśli potrzebujesz uznania za swoja prace nad tłumaczeniem proponuje założenie własnej strony na FB a nie usuwanie ludzi których nie lubisz.

**Comment by Kunegard** [comment]
Polacy to jednak bardzo zabawny naród. Kłóci się taki o swoje, kłóci, jakby co najmniej tłumaczenie Rima i wpisanie w autorów zapewniało mu sławę i dobrobyt. No po prostu... 
Mam do Was prośbę: skoro Nalthe (i analogicznie ja) jesteśmy dla Was mili, hej, może też bądźcie mili? MaxDyner na wstępie - po nieodzywaniu się x czasu - wyleciał z dość niemiłymi słówkami.
Czemu do jasnej kurwy problem jest tylko z Polakami?

Zanim dojdzie do "a bo Ty", z przyjemnością poinformuję, że nie w każdej swojej pracy mogłem się podpisać, choć praw osobistych nikt mi nie ma prawa odebrać.

**Comment by hapalupa** [comment]
Cóż za absurd, próbujesz przedstawić sytuacje jak by to tylko @maxdyner zachowywał się niedorzecznie, tymczasem @Nalthe w odpowiedzi żali się że nie jest uwzględniona w największym polskim fanpage Rimworlda na FB, tak jak by miało to jej przynieść  "sławę i dobrobyt"... Nie rozumiem, sam sobie tłumaczyłem rimworlda bo polska wersja dostarczana z grą miała na początku wiele błędów (a nie wiedziałem jeszcze że jest tłumaczenie na github), więc wiem że nawet po zmianie wersji większość plików z poprzednim tłumaczeniem zostaje. Naturalnie nawet poprawiając błędy i dodając nowe linijki kodu bazujesz na podstawowym tłumaczeniu nad którym ktoś poświęcił czas, więc nie powinno dziwić że ktoś może mieć pretensje że jego imię zostało usunięte.
Nie zrozum mnie źle, nikt nie zaprzecza że robicie dobrą robotę z tym tłumaczeniem i że poświęcacie na nie dużo czasu, w szczególności @Nalthe, ale jeżeli komuś zależy żeby być w creditsach i poświęcił swój czas na pracę nad tłumaczeniem to powinien mieć taką możliwość.

**Comment by 2piotrek** [comment]
Sekcja w creditsach jest dla każdej osoby która pracowała nad tłumaczeniem. Jest to swoiste wynagrodzenie za włożoną prace.

**Comment by ByJacob** [comment]
Zamykam wątek - jest już stary
