### ISSUE TITLE
Są tu jacyś zawodowi tłumacze, albo studenci translatoryki?

### ISSUE THREAD

**Issue by Szszymon14** [Ludeon/RimWorld-Polish#54]
Jak wyżej. Pytam ponieważ rozważam wzięcie pod lupę tego projektu jako dobrego materiauł do napisania pracy licencjackiej o tłumaczeniach nieprofesjonalnych.

**Comment by westwinnd** [comment]
#Nie ja. :>

**Comment by Szszymon14** [comment]
Więc wszyscy robili to amatorsko?

**Comment by Szszymon14** [comment]
To dobrze, będzie dużo błędów do analizowania. Może przy okazji sam wspomogę w tłumaczeniu. :)

**Comment by westwinnd** [comment]
Jeden z byłych członków zespołu (Nalthe), jest zawodowym tłumaczem.

**Comment by kerberois** [comment]
To nie jest umowa międzynarodowa by trzeba było tłumaczy przysięgłych ;)

Dnia 11 czerwca 2018 09:00:20 CEST, "Marcin Z." <notifications@github.com> napisał(a):
>Jeden z byłych członków zespołu (Nalthe), jest zawodowym tłumaczem.
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Ludeon/RimWorld-Polish/issues/54#issuecomment-396141742

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Szszymon14** [comment]
Dobra, ten pomysł już porzuciłem. Zbyt ambitnie i chaotycznie. :(
