### ISSUE TITLE
1.0

### ISSUE THREAD

**Issue by SirVakari** [Ludeon/RimWorld-Polish#55]
Uszanowanie.
Aktualnie przymierzam się do obrobienia całego Rima tak więc pozostawiam tu pytanie - w razie gdyby pojawił się jeszcze ktoś chętny.

**Comment by kerberois** [comment]
Ale po co wyważać otwarte drzwi?

Dnia 12 lipca 2018 03:23:42 CEST, Vakari Rajfun <notifications@github.com> napisał(a):
>Uszanowanie.
>Aktualnie przymierzam się do obrobienia całego Rima tak więc
>pozostawiam tu pytanie - w razie gdyby pojawił się jeszcze ktoś chętny.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Ludeon/RimWorld-Polish/issues/55

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by westwinnd** [comment]
Masz jakiś plan odnośnie organizacji? ;]

**Comment by SirVakari** [comment]
@kerberois 
Jeżeli masz na myśli fakt tego, iż opracowane były poprzednie wersje to nie bój żaby - jestem tego świadom. Nie wiadomo jeszcze jak wiele zostanie zmienione w następnej wersji w kwestii podstawowego buildu z B18, a także ile w sumie kontentu zostanie dodane. (Aktualnie trwają bugfixy, więc wole się wstrzymać od brania dostępnej wersji za ostateczną. Nie mamy tutaj tak zorganizowanej grupy jak za przykładem Czesi, którzy nawet drobne unstable-patche aktualizowali na przełomie paru godzin.)

@westwinnd 
Pierwszym punktem tego planu jest upewnienie się ilu ludzi będzie w chęci i możliwości.  : ]

**Comment by GreenGas48** [comment]
Uszanowanko,
Nowy tłumacz tutaj, mam zamiar tłumaczyć powoli wszystko, ale moim głównym celem będzie naprawienie nazw miejsc (na mapie świata), bo Daleki Green Dolina jest trochę nieporęczne, a tak to wygląda w większości przypadków. Ale jak chcecie, możemy zacząć jakieś kooperacyjne tłumaczenie. Napiszcie mi maila.

**Comment by klawyMarcin** [comment]
Po aktywności, jaka tu jest, myślę, że możesz spokojnie tłumaczyć na bieżąco, co Ci się podoba :P

**Comment by panyann** [comment]
Kto wie, może też coś skrobnę.

**Comment by panyann** [comment]
Hej... Trochę nowy jestem, jeśli chodzi o kolaborację na GitHubie... Próbuję wysłać brancha i dostaję permission denied. Jak poprawnie pushować zmiany?

**Comment by werranik** [comment]
> Hej... Trochę nowy jestem, jeśli chodzi o kolaborację na GitHubie... Próbuję wysłać brancha i dostaję permission denied. Jak poprawnie pushować zmiany?


https://ludeon.com/forums/index.php?topic=2933.0
musisz zrobić requesta z prośbą o dodanie do gita, domyślnie możesz tylko pobrać brancha.

**Comment by Arczi008TV** [comment]
Sporo poprawiłem i przetłumaczyłem, a widzę ze tutaj  nic się nie dzieje, ktoś to jeszcze nadzoruje?

**Comment by werranik** [comment]
Ta, też mam paczkę do wrzucenia, zmerguje z Twoim i pushne w wolnej chwili.

**Comment by GreenGas48** [comment]
Ej patrzcie bo jest pewna sprawa:
Dlaczego my dyskutujemy publicznie? Pytanie "Hej kto tłumaczy 1.0 ze mną" nie jest problemem z tym repo! Powinniśmy usunąć ten issue I pisać w collaborator discussions (z których nikt tutaj nie korzysta). Przy okazji zerknijcie sobie tam bo jest tam jeden problem na który nikt nie odpisał a jest dość istotny. Uszanowanko

**Comment by Arczi008TV** [comment]
Pytanie nie brzmi "Hej kto tłumaczy 1.0 ze mną" tylko, "gdzie do jasnej anielki jest?" a to już jest problem

**Comment by GreenGas48** [comment]
No dobra niech ci będzie, ale weźcie ktoś zerknij na tą dyskusje co ją zacząłem bo mam wrażenie że wszyscy czytają issues ale już team discussions nie.
Nie wiem czy link zadziała:
https://github.com/orgs/Ludeon/teams/translators-polish/discussions/1
a tak btw: *@Arczi008TV to ty jesteś tym typem od Leopolda?*

**Comment by Arczi008TV** [comment]
Nie mam dostępu bo nie jestem członkiem, niedawno założyłem konto.

Tak jestem od Leopolda..

**Comment by GreenGas48** [comment]
Jeśli pomagasz w tłumaczeniu i jesteś w miarę aktywny to po prostu napisz do Michaela na ludeonhelp@gmail.com że chcesz tłumaczyć i bez żadnych ceregieli doda cię to teamu.
Do wszystkich kto JEST w teamie: ***Zobaczcie tą dyskusję***

**Comment by Arczi008TV** [comment]
Ciekawe kto ma zobaczyć jak tu nikogo nie ma

**Comment by ByJacob** [comment]
Po wszelakie pytania zapraszam aktywnych członków do teamu Translators - Polish. Zamykam Wątek
