### ISSUE TITLE
Co się stało z nowym tłumaczeniem?

### ISSUE THREAD

**Issue by Ahinana** [Ludeon/RimWorld-Polish#64]
Nie wiem, kto wymyślił, by "poprawić" nazwy cech, ale to był zdecydowanie strzał w kolano tego tłumaczenia. Wszystkie przymiotniki cech zostały zamienione na rzeczowniki, okej, w niektórych przypadkach inaczej się nie dało, ale serio, czy komuś przeszkadzała męska odmiana? Nie wiem komu bardziej pasowało atrakcyjnośc i duża atrakcyjność, zamiast ładny i piękny. Osobie, która to zmieniała naprawde przydałby się porządny słownik, tłumaczyć tough na twardość, ręce opadają. Wiele błędów w stringach, niepodmykane {gendery}, jak już są te gendery, to czemu by nie zrobić cech w genderowych odmianach. 
Rośliny teraz są "roślinami"(a część roślin z powrotem jest po angielsku) w menu to wygląda: "roślina: roślina ziemniaka". Trochę przesada. 

Zaraz pewnie powiecie, że marudzić zawsze łatwo, ja jednak nie zamierzam pozwolić, by moja ulubiona gra była w takim stanie i wkrótce zabiorę się za poprawianie tego "poprawienia".

**Comment by ByJacob** [comment]
Hej
Przykro nam że tak to wygląda aktualnie, ale na bieżąco staramy się poprawić wszelakie błędy. Po wydaniu wersji 1.0 były bardzo duże zmiany w strukturze tłumaczeń, oraz za dużo osób nie było do tłumaczenia, i były one robione na szybko. Dlatego wygląda to niestety tak jak wygląda. Też przez takie zmiany postanowiłem pracować nad tłumaczeniami.

W celu pomocy zapraszam pod link [Jak zacząć tłumaczenia](https://ludeon.com/forums/index.php?topic=2933.0) aby nam w tym pomóc. Aktualnie są 2 osoby które starają się to wszystko poprawiać w wolnym czasie (ja na przykład w pracy robię tłumaczenia).

Poza tym przeglądając tłumaczenia innych języków też nie ma dużo rzeczy porobionych jeszcze, a poza tym język polski jest trudny do przetłumaczenia ze względu na gramatykę.

**Comment by VATICANPSYCHO** [comment]
Zamiast marudzić na cudzą pracę, najpierw warto zastanowić się czy samemu jest się bez winy. Jeśli widzi się, że ktoś robi coś źle, najpierw zwrócić mu uwagę na to oraz dać ma wkazówki dotyczące dalszego planowania. Wielu było ludzi, którzy nie potrafili przemóc się do takiej postawy.

W starożytności takie osoby, często wysoko postawione, okazywały się zdrajcami.

**Comment by Arczi008TV** [comment]
> zamiast ładny i piękny.

"Marta jest piękny"  no rzeczywiście pasuje. To jest tłumaczenie beta, wszystko do poprawy i dyskusji. Jak by działał ten kod gender   to by można było dać "piękny ; piękna" to by było ok.
