### ISSUE TITLE
Czemu cofnięto tłumaczenie z master?

### ISSUE THREAD

**Issue by Arczi008TV** [Ludeon/RimWorld-Polish#73]
ByJacob, czemu jest revert? 

Ogólnie to nie wiedziałem, że ktoś tu jeszcze tłumaczy, bo samemu zamierzałem przetłumaczyć wszystko, a sporo już przetłumaczyłem. A na stronce zobaczyłem, że coś się dzieje :D

**Comment by ByJacob** [comment]
Hej 😀 ponieważ robiłeś to na starym kodzie. Zajrzyj do naszego zespołu na Ludeon, tam znajdziesz niezbędne informacje 😀

**Comment by Arczi008TV** [comment]
No jakoś kiepsko mi idzie szukanie. Jakiś link :)?

**Comment by ByJacob** [comment]
> Na starym kodzie? Hhmm nie wiem, oczyściłem tłumaczenie przy użyciu najnowszej wersji, które i tak nic nie wnosi, dodaje jedną spacje na końcu. Jedyna sensowna zmiana to w pliku backstories jakieś nowe linijki do tłumaczenia zostają dodane i tyle. A w Twoim branchu jest dużo "czyszczenia tłumaczeń". Nic z tego nie rozumiem ;d
> ![changes](https://user-images.githubusercontent.com/49120706/60971693-097fd200-a325-11e9-902c-088f29270fa9.png)
> 
> No jakoś kiepsko mi idzie szukanie tego zespołu. Jakiś link :)?

[https://github.com/orgs/Ludeon/teams/translators-polish/discussions?pinned=1](Proszę link)
